services:
  backend:
    build:
      context: ./backend
    volumes:
      - ./backend:/app
      - ./paper_agent:/app/paper_agent
    ports:
      - 8000:8000
    env_file:
      - ./backend/.env
    command: uvicorn main:app --host 0.0.0.0 --port 8000
